//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ContractManagementData
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Agreement))]
    [KnownType(typeof(ExternalPerson))]
    [KnownType(typeof(ExternalRole))]
    public partial class Agreement_ResponsibleExternal
    {
        #region Primitive Properties
        [DataMember]
        public virtual int ID
        {
            get;
            set;
        }
        [DataMember]
        public virtual int Agreement_id
        {
            get { return _agreement_id; }
            set
            {
                if (_agreement_id != value)
                {
                    if (Agreement != null && Agreement.ID != value)
                    {
                        Agreement = null;
                    }
                    _agreement_id = value;
                }
            }
        }
        private int _agreement_id;
        [DataMember]
        public virtual int ExternalRole_id
        {
            get { return _externalRole_id; }
            set
            {
                if (_externalRole_id != value)
                {
                    if (ExternalRole != null && ExternalRole.ID != value)
                    {
                        ExternalRole = null;
                    }
                    _externalRole_id = value;
                }
            }
        }
        private int _externalRole_id;
        [DataMember]
        public virtual int ExternalPerson_id
        {
            get { return _externalPerson_id; }
            set
            {
                if (_externalPerson_id != value)
                {
                    if (ExternalPerson != null && ExternalPerson.ID != value)
                    {
                        ExternalPerson = null;
                    }
                    _externalPerson_id = value;
                }
            }
        }
        private int _externalPerson_id;

        #endregion

        #region Navigation Properties
        
    
        [DataMember]
        public virtual Agreement Agreement
        {
            get { return _agreement; }
            set
            {
                if (!ReferenceEquals(_agreement, value))
                {
                    var previousValue = _agreement;
                    _agreement = value;
                    FixupAgreement(previousValue);
                }
            }
        }
        private Agreement _agreement;
        
    
        [DataMember]
        public virtual ExternalPerson ExternalPerson
        {
            get { return _externalPerson; }
            set
            {
                if (!ReferenceEquals(_externalPerson, value))
                {
                    var previousValue = _externalPerson;
                    _externalPerson = value;
                    FixupExternalPerson(previousValue);
                }
            }
        }
        private ExternalPerson _externalPerson;
        
    
        [DataMember]
        public virtual ExternalRole ExternalRole
        {
            get { return _externalRole; }
            set
            {
                if (!ReferenceEquals(_externalRole, value))
                {
                    var previousValue = _externalRole;
                    _externalRole = value;
                    FixupExternalRole(previousValue);
                }
            }
        }
        private ExternalRole _externalRole;

        #endregion

        #region Association Fixup
    
        private void FixupAgreement(Agreement previousValue)
        {
            if (previousValue != null && previousValue.Agreement_ResponsibleExternal.Contains(this))
            {
                previousValue.Agreement_ResponsibleExternal.Remove(this);
            }
    
            if (Agreement != null)
            {
                if (!Agreement.Agreement_ResponsibleExternal.Contains(this))
                {
                    Agreement.Agreement_ResponsibleExternal.Add(this);
                }
                if (Agreement_id != Agreement.ID)
                {
                    Agreement_id = Agreement.ID;
                }
            }
        }
    
        private void FixupExternalPerson(ExternalPerson previousValue)
        {
            if (previousValue != null && previousValue.Agreement_ResponsibleExternal.Contains(this))
            {
                previousValue.Agreement_ResponsibleExternal.Remove(this);
            }
    
            if (ExternalPerson != null)
            {
                if (!ExternalPerson.Agreement_ResponsibleExternal.Contains(this))
                {
                    ExternalPerson.Agreement_ResponsibleExternal.Add(this);
                }
                if (ExternalPerson_id != ExternalPerson.ID)
                {
                    ExternalPerson_id = ExternalPerson.ID;
                }
            }
        }
    
        private void FixupExternalRole(ExternalRole previousValue)
        {
            if (previousValue != null && previousValue.Agreement_ResponsibleExternal.Contains(this))
            {
                previousValue.Agreement_ResponsibleExternal.Remove(this);
            }
    
            if (ExternalRole != null)
            {
                if (!ExternalRole.Agreement_ResponsibleExternal.Contains(this))
                {
                    ExternalRole.Agreement_ResponsibleExternal.Add(this);
                }
                if (ExternalRole_id != ExternalRole.ID)
                {
                    ExternalRole_id = ExternalRole.ID;
                }
            }
        }

        #endregion

    }
}
