//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ContractManagementData
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Agreement_SalesActual))]
    public partial class ExpiryCategory
    {
        #region Primitive Properties
        [DataMember]
        public virtual int ID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Caption
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<Agreement_SalesActual> Agreement_SalesActual
        {
            get
            {
                if (_agreement_SalesActual == null)
                {
                    var newCollection = new FixupCollection<Agreement_SalesActual>();
                    newCollection.CollectionChanged += FixupAgreement_SalesActual;
                    _agreement_SalesActual = newCollection;
                }
                return _agreement_SalesActual;
            }
            set
            {
                if (!ReferenceEquals(_agreement_SalesActual, value))
                {
                    var previousValue = _agreement_SalesActual as FixupCollection<Agreement_SalesActual>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAgreement_SalesActual;
                    }
                    _agreement_SalesActual = value;
                    var newValue = value as FixupCollection<Agreement_SalesActual>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAgreement_SalesActual;
                    }
                }
            }
        }
        private ICollection<Agreement_SalesActual> _agreement_SalesActual;

        #endregion

        #region Association Fixup
    
        private void FixupAgreement_SalesActual(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Agreement_SalesActual item in e.NewItems)
                {
                    item.ExpiryCategory = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Agreement_SalesActual item in e.OldItems)
                {
                    if (ReferenceEquals(item.ExpiryCategory, this))
                    {
                        item.ExpiryCategory = null;
                    }
                }
            }
        }

        #endregion

    }
}
