//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ContractManagementData
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Agreement_ResponsibleExternal))]
    public partial class ExternalPerson
    {
        #region Primitive Properties
        [DataMember]
        public virtual int ID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string UniqueName
        {
            get;
            set;
        }
        [DataMember]
        public virtual string LastName
        {
            get;
            set;
        }
        [DataMember]
        public virtual string FirstName
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<Agreement_ResponsibleExternal> Agreement_ResponsibleExternal
        {
            get
            {
                if (_agreement_ResponsibleExternal == null)
                {
                    var newCollection = new FixupCollection<Agreement_ResponsibleExternal>();
                    newCollection.CollectionChanged += FixupAgreement_ResponsibleExternal;
                    _agreement_ResponsibleExternal = newCollection;
                }
                return _agreement_ResponsibleExternal;
            }
            set
            {
                if (!ReferenceEquals(_agreement_ResponsibleExternal, value))
                {
                    var previousValue = _agreement_ResponsibleExternal as FixupCollection<Agreement_ResponsibleExternal>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAgreement_ResponsibleExternal;
                    }
                    _agreement_ResponsibleExternal = value;
                    var newValue = value as FixupCollection<Agreement_ResponsibleExternal>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAgreement_ResponsibleExternal;
                    }
                }
            }
        }
        private ICollection<Agreement_ResponsibleExternal> _agreement_ResponsibleExternal;

        #endregion

        #region Association Fixup
    
        private void FixupAgreement_ResponsibleExternal(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Agreement_ResponsibleExternal item in e.NewItems)
                {
                    item.ExternalPerson = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Agreement_ResponsibleExternal item in e.OldItems)
                {
                    if (ReferenceEquals(item.ExternalPerson, this))
                    {
                        item.ExternalPerson = null;
                    }
                }
            }
        }

        #endregion

    }
}
