//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ContractManagementData
{
    [DataContract(IsReference = true)]
    public partial class ImportBulk
    {
        #region Primitive Properties
        [DataMember]
        public virtual string RefBelegtyp
        {
            get;
            set;
        }
        [DataMember]
        public virtual string RefBelegnummer
        {
            get;
            set;
        }
        [DataMember]
        public virtual int RefBelegzeile
        {
            get;
            set;
        }
        [DataMember]
        public virtual int Buchungsperiode
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Profitcenter
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Kontonummer
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Bezeichnung
        {
            get;
            set;
        }
        [DataMember]
        public virtual string InProfitCenterHauswaehrung
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Waehrung
        {
            get;
            set;
        }
        [DataMember]
        public virtual string PSPElement
        {
            get;
            set;
        }
        [DataMember]
        public virtual string WBSElementText
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Material
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Text
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Debitor
        {
            get;
            set;
        }

        #endregion

    }
}
