//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ContractManagementData
{
    [DataContract(IsReference = true)]
    public partial class ImportOption
    {
        #region Primitive Properties
        [DataMember]
        public virtual string ImportProfile
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ImportFilePath
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ImportFilePattern
        {
            get;
            set;
        }
        [DataMember]
        public virtual string FieldTerminator
        {
            get;
            set;
        }
        [DataMember]
        public virtual string RowTerminator
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ServerName
        {
            get;
            set;
        }

        #endregion

    }
}
