//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ContractManagementData
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Agreement_ResponsibleInternal))]
    public partial class InternalRole
    {
        #region Primitive Properties
        [DataMember]
        public virtual int ID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Caption
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<Agreement_ResponsibleInternal> Agreement_ResponsibleInternal
        {
            get
            {
                if (_agreement_ResponsibleInternal == null)
                {
                    var newCollection = new FixupCollection<Agreement_ResponsibleInternal>();
                    newCollection.CollectionChanged += FixupAgreement_ResponsibleInternal;
                    _agreement_ResponsibleInternal = newCollection;
                }
                return _agreement_ResponsibleInternal;
            }
            set
            {
                if (!ReferenceEquals(_agreement_ResponsibleInternal, value))
                {
                    var previousValue = _agreement_ResponsibleInternal as FixupCollection<Agreement_ResponsibleInternal>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAgreement_ResponsibleInternal;
                    }
                    _agreement_ResponsibleInternal = value;
                    var newValue = value as FixupCollection<Agreement_ResponsibleInternal>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAgreement_ResponsibleInternal;
                    }
                }
            }
        }
        private ICollection<Agreement_ResponsibleInternal> _agreement_ResponsibleInternal;

        #endregion

        #region Association Fixup
    
        private void FixupAgreement_ResponsibleInternal(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Agreement_ResponsibleInternal item in e.NewItems)
                {
                    item.InternalRole = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Agreement_ResponsibleInternal item in e.OldItems)
                {
                    if (ReferenceEquals(item.InternalRole, this))
                    {
                        item.InternalRole = null;
                    }
                }
            }
        }

        #endregion

    }
}
