//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ContractManagementData
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Agreement_Memo))]
    public partial class MemoType
    {
        #region Primitive Properties
        [DataMember]
        public virtual int ID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Caption
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<Agreement_Memo> Agreement_Memo
        {
            get
            {
                if (_agreement_Memo == null)
                {
                    var newCollection = new FixupCollection<Agreement_Memo>();
                    newCollection.CollectionChanged += FixupAgreement_Memo;
                    _agreement_Memo = newCollection;
                }
                return _agreement_Memo;
            }
            set
            {
                if (!ReferenceEquals(_agreement_Memo, value))
                {
                    var previousValue = _agreement_Memo as FixupCollection<Agreement_Memo>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAgreement_Memo;
                    }
                    _agreement_Memo = value;
                    var newValue = value as FixupCollection<Agreement_Memo>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAgreement_Memo;
                    }
                }
            }
        }
        private ICollection<Agreement_Memo> _agreement_Memo;

        #endregion

        #region Association Fixup
    
        private void FixupAgreement_Memo(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Agreement_Memo item in e.NewItems)
                {
                    item.MemoType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Agreement_Memo item in e.OldItems)
                {
                    if (ReferenceEquals(item.MemoType, this))
                    {
                        item.MemoType = null;
                    }
                }
            }
        }

        #endregion

    }
}
